### ISSUE TITLE
Missing dependency and .flair() function not available.

### ISSUE THREAD

**Issue by fahadysf** [secretum-inc/quo#18]
**Describe the bug**
wcwidth is a required module but deosn't get installed when installing quo via pip.
The examples refer to quo.flair() but it doesn't seem to have such a function

**To Reproduce**
>>> import quo
>>> quo.flair(f'Hello, World!', fg="red", bold=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'quo' has no attribute 'flair'

**Expected behavior**
.flair() function should be available

**Screenshots**
![image](https://user-images.githubusercontent.com/3066248/126216763-ed5a956c-76bf-4ee0-9319-ba9bc5be2b75.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX Big Sur with Homebrew
 - Python 3.9.6 (installed via Homebrew).

**Comment by gerrishons** [comment]
Hello! Kindly use echo() instead of flair()  thank you

**Comment by gerrishons** [comment]
@fahadysf Use echo() instead of flair()

**Comment by fahadysf** [comment]
That works. Thanks. Readme / Docs probably need cleanup

**Comment by gerrishons** [comment]
@fahadysf wcwidth dendency issue was resolved install quo==2021.3.5 to get the updated version

**Comment by gerrishons** [comment]
#
